name: build-osx-binary
on:
  workflow_call:
    inputs:
      arch:
        description: "Architecture (x86_64 or aarch64)"
        required: false
        default: "aarch64"
        type: string
  workflow_dispatch: null

jobs:

  build-self-contained-osx-binary:
    runs-on: ${{ inputs.arch == 'x86_64' && 'macos-13-large' || 'macos-13-xlarge' }}
    steps:
      - name: Install ccache
        run: |
          brew install ccache
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set Nuitka cache dir
        run: echo "NUITKA_CACHE_DIR=${{ github.workspace }}/_nuitka" >> $GITHUB_ENV

      - name: Make GHA cache invariant to opengrep version
        run: |
          rm cli/src/semgrep/__init__.py

      - name: Set GHA cache for Nuitka
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # ratchet:actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ runner.arch }}-v1-nuitka-${{ hashFiles('cli/src/semgrep/**/*.py') }}
          path: "${{ env.NUITKA_CACHE_DIR }}"

      - name: Install pipenv
        run: |
          python -m pip install --no-cache-dir --upgrade pipenv
      - name: Install pyinstaller
        run: pipenv run pip install nuitka protobuf jaraco.text

      - name: install some dependencies for windows (pyinstaller only)
        run: pipenv run pip install chardet charset-normalizer

      - uses: actions/download-artifact@b14cf4c92620c250e1c074ab0a5800e37df86765 # ratchet:actions/download-artifact@v4
        with:
          name: osx-${{ inputs.arch == 'x86_64' && 'x86' || 'arm64' }}-wheel

      # - name: Authenticate GitHub CLI
      #   run: |
      #     gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      # - name: Get Latest Successful Run ID
      #   id: get-run-id
      #   run: |
      #     # Fetch the latest successful run ID for the workflow
      #     RUN_ID=$(gh run list --repo opengrep/opengrep --workflow build-test-osx-arm64 --status success --limit 1 --json databaseId --jq '.[0].databaseId')
      #     echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      # - name: Output Run ID
      #   run: |
      #     echo "The latest successful run ID is: ${{ steps.get-run-id.outputs.run_id }}"

      # - name: Download Artifact
      #   run: |
      #     gh run download ${{ steps.get-run-id.outputs.run_id }} \
      #       -R opengrep/opengrep -n osx-${{ inputs.arch == 'x86_64' && 'x86' || 'arm64' }}-wheel
          
      - run: unzip dist.zip

      - name: Install opengrep
        run: |
          pipenv run pip install dist/*.whl
          unzip dist/*.whl -d _wheel

      - name: Export OPENGREP_VERSION
        run: echo "OPENGREP_VERSION=$(pipenv run opengrep --version)" >> $GITHUB_ENV
        shell: bash

      - name: Set SRC_SEMGREP_DIR with wheel contents
        run: |
          echo \
          "SRC_SEMGREP_DIR=\
          ${GITHUB_WORKSPACE}/_wheel/opengrep-$OPENGREP_VERSION.data/purelib/semgrep" \
          >> $GITHUB_ENV

      - name: Build executable
        run: |
          pipenv run bash ./scripts/build-nuitka.sh "v$OPENGREP_VERSION" true $SRC_SEMGREP_DIR

      - name: Zip artifact
        run: zip -j opengrep.zip cli/opengrep

      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # ratchet:actions/upload-artifact@v4
        with:
          name: opengrep_osx_binary_${{ inputs.arch == 'x86_64' && 'x86' || 'arm64' }}
          path: opengrep.zip 

  test-osx-binary:
    needs: build-self-contained-osx-binary
    runs-on: ${{ inputs.arch == 'x86_64' && 'macos-13-large' || 'macos-13-xlarge' }}
    steps:
      - uses: actions/download-artifact@b14cf4c92620c250e1c074ab0a5800e37df86765 # ratchet:actions/download-artifact@v4
        with:
          name: opengrep_osx_binary_${{ inputs.arch == 'x86_64' && 'x86' || 'arm64' }}
      - run: unzip opengrep.zip
      - run: chmod +x opengrep 
      - run: |
          ./opengrep --version
      - run: |
          ./opengrep --help
      - run: |
          echo '1 == 1' | ./opengrep -l python -e '$X == $X' -
